# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos7/kernel5.4"
  config.vm.box_check_update = false
  config.vm.network "private_network", ip: "10.102.1.10"
  config.vm.provider "virtualbox" do |v|
    v.memory = 3096 
    v.cpus = 2
  end
end
    
