# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box_check_update = false
  config.vm.box = "DeyunLuo/centos7"
  config.vm.provider 'virtualbox' do |vb|
   vb.customize [ "guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold", 1000 ]
  end
  $num_instances = 2
  (1..$num_instances).each do |i|
    config.vm.define "k8s#{i}" do |node|
      ip = "10.10.1.#{i+10}"
      node.vm.hostname = "k8s#{i}"
      node.vm.network "private_network", ip: ip
      node.vm.provider "virtualbox" do |vb|
        vb.memory = 3096
        vb.cpus = 2
        vb.name = "k8s#{i}"
      end
    end
   end
end
