# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "DeyunLuo/centos7"
  config.vm.box_check_update = false
  config.vm.hostname = "k8s-master"
  config.vm.network "private_network", ip: "10.102.1.10"
  config.vm.provider "virtualbox" do |v|
    v.memory = 3096 
    v.cpus = 2
    v.name = "k8s-master"
  end
end
    
